services:
  domen-mail:
    build:
      context: .
      dockerfile: Dockerfile
    image: ${DOCKER_IMAGE:-domen-mail:1.0.0}
    container_name: domen-mail
    restart: unless-stopped
    ports:
      - "${PORT:-3000}:3000"
    environment:
      PORT: "3000"
      IMAP_HOST: ${IMAP_HOST:-imap.beget.com}
      IMAP_PORT: ${IMAP_PORT:-993}
      IMAP_TLS: ${IMAP_TLS:-true}
